version: '3'

services:
  api: # service名
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - .:/go/api
    ports:
      - '3000:3000'
  db:
    image: mysql:8.0
    container_name: dbContainer
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: go_database # database名
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d

volumes:
  dbdata:
    driver: local
